name: issue
on:
  issues:
    types: [opened]
permissions: write-all
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Rick Roll
      uses: TejasvOnly/random-rickroll@v1.0
      with:
        percentage: 100
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
